---
Name: 'DragonUncaged'
Github: 'https://github.com/DragonUncaged'
WebSite: 'https://www.linkedin.com/in/ankitrao/'
Problem: 'Print The Alll The subsequences Of String'
Description: ' A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.'
Explanation: 'One by one fix characters and recursively generates all subsets starting from them.'
Language: 'c++' 
---
```c++
/**
Ex. 
Input:
abc
Output:
abc
ab
ac
a
bc
b
c
(empty)   

    One by one fix characters and recursively generates all subsets starting from them.
    After every recursive call, we remove last character so that the next permutation can be generated. 

*/
#include "bits/stdc++.h"
using namespace std;

vector<char> v;
vector<vector<char>> result;

void subSequence(string &str, int i)
{
    if (i == str.size())
    {
        result.push_back(v);
        return;
    }
    char c = str[i];
    v.push_back(c);
    subSequence(str, i + 1); //call for inclusion  O(1)
    v.pop_back();            //restore to original;
    subSequence(str, i + 1); //call for exclusion
}

int main()
{
    string str;
    cin >> str;
    //v and result are declared globally
    v.reserve(str.size());
    result.reserve(1 << (str.size()));
    subSequence(str, 0);

    for (auto &row : result)
    {
        if (row.size() == 0)
        {
            cout << "(empty)\n";
            continue;
        }

        for (auto &el : row)
            cout << el;
        cout << "\n";
    }

    return 0;
}


```